### ISSUE TITLE
Crash in libballyhoo_handle_input_cb

### ISSUE THREAD

**Issue by mdillavou** [line72/helplightning-libpurple#17]
```
Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
Downloading source file /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/libpurple/plugins/ssl/ssl-nss.c
0x0000ffffe5260ea4 in ssl_nss_read (gsc=<optimized out>, data=0x155555760dce8, len=2501951) at /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/libpurple/plugins/ssl/ssl-nss.c:535                                                               
535		ret = PR_Read(nss_data->in, data, len);
(gdb) bt
#0  0x0000ffffe5260ea4 in ssl_nss_read (gsc=<optimized out>, data=0x155555760dce8, len=2501951) at /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/libpurple/plugins/ssl/ssl-nss.c:535
#1  0x0000ffffe60e2578 [PAC] in libballyhoo_handle_input_cb (gsc=<optimized out>, cond=<optimized out>, data=<optimized out>) at src/libballyhoo.c:312
#2  libballyhoo_handle_input_cb (data=0xaaaaabbd8ce0, gsc=<optimized out>, cond=<optimized out>) at src/libballyhoo.c:290
#3  0x0000aaaaaab1be38 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=<optimized out>) at /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/pidgin/gtkeventloop.c:73
#4  0x0000fffff6cd09b4 [PAC] in g_main_dispatch (context=0xaaaaaac04970) at ../glib/gmain.c:3344
#5  g_main_context_dispatch_unlocked (context=0xaaaaaac04970) at ../glib/gmain.c:4152
#6  0x0000fffff6d35744 [PAC] in g_main_context_iterate_unlocked.isra.0 (context=0xaaaaaac04970, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4217
#7  0x0000fffff6cd6dd0 [PAC] in g_main_loop_run (loop=0xaaaaab921c40) at ../glib/gmain.c:4419
#8  0x0000fffff795a9a0 [PAC] in IA__gtk_main () at /usr/src/debug/gtk2-2.24.33-18.fc40.aarch64/gtk/gtkmain.c:1270
#9  0x0000aaaaaaae78e8 [PAC] in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/pidgin/gtkmain.c:947
(gdb) thread
[Current thread is 1 (Thread 0xfffff7f83020 (LWP 74606))]
```

**Comment by mdillavou** [comment]
A similar traceback:
```
Thread 1 "pidgin" received signal SIGPIPE, Broken pipe.
0x0000fffff6944d54 in __libc_send (fd=52, buf=0xaaaaab31d190, len=31, flags=0) at ../sysdeps/unix/sysv/linux/send.c:28
28	  return SYSCALL_CANCEL (sendto, fd, buf, len, flags, NULL, 0);
(gdb) bt
#0  0x0000fffff6944d54 in __libc_send (fd=52, buf=0xaaaaab31d190, len=31, flags=0) at ../sysdeps/unix/sysv/linux/send.c:28
#1  __libc_send (fd=52, buf=buf@entry=0xaaaaab31d190, len=len@entry=31, flags=flags@entry=0) at ../sysdeps/unix/sysv/linux/send.c:23
#2  0x0000ffffe53bd05c [PAC] in pt_Send (fd=0xaaaaab3f57d0, buf=0xaaaaab31d190, amount=31, flags=0, timeout=4294967295) at ../../../../nspr/pr/src/pthreads/ptio.c:2002
#3  0x0000ffffe56ee3c0 [PAC] in ssl_DefSend (ss=ss@entry=0xaaaaab318950, buf=0xaaaaab31d190 "\025\003\003", len=31, flags=flags@entry=0) at ssldef.c:105
#4  0x0000ffffe56d6750 [PAC] in ssl3_SendRecord (ss=ss@entry=0xaaaaab318950, cwSpec=cwSpec@entry=0x0, ct=ct@entry=ssl_ct_alert, pIn=0xffffffffbf92 "\377\377\377\377", pIn@entry=0xffffffffbf90 "\001", nIn=0, 
    nIn@entry=2, flags=flags@entry=0) at ssl3con.c:2605
#5  0x0000ffffe56d6d3c [PAC] in SSL3_SendAlert (ss=ss@entry=0xaaaaab318950, level=level@entry=alert_warning, desc=desc@entry=close_notify) at ssl3con.c:2930
#6  0x0000ffffe56f3d9c [PAC] in ssl_SecureClose (ss=0xaaaaab318950) at sslsecur.c:744
#7  0x0000ffffe5260e34 [PAC] in ssl_nss_close (gsc=0xaaaaabc86fb0) at /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/libpurple/plugins/ssl/ssl-nss.c:512
#8  0x0000fffff735f55c [PAC] in purple_ssl_close (gsc=0xaaaaabc86fb0) at /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/libpurple/sslconn.c:247
#9  0x0000ffffe60e2a44 [PAC] in libballyhoo_handle_input_cb (gsc=<optimized out>, cond=<optimized out>, data=<optimized out>) at src/libballyhoo.c:496
#10 libballyhoo_handle_input_cb (data=0xaaaaabab1470, gsc=<optimized out>, cond=<optimized out>) at src/libballyhoo.c:290
#11 0x0000aaaaaab1be38 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=<optimized out>) at /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/pidgin/gtkeventloop.c:73
#12 0x0000fffff6cd09b4 [PAC] in g_main_dispatch (context=0xaaaaaac04970) at ../glib/gmain.c:3344
#13 g_main_context_dispatch_unlocked (context=0xaaaaaac04970) at ../glib/gmain.c:4152
#14 0x0000fffff6d35744 [PAC] in g_main_context_iterate_unlocked.isra.0 (context=0xaaaaaac04970, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4217
#15 0x0000fffff6cd6dd0 [PAC] in g_main_loop_run (loop=0xaaaaab9208c0) at ../glib/gmain.c:4419
#16 0x0000fffff795a9a0 [PAC] in IA__gtk_main () at /usr/src/debug/gtk2-2.24.33-18.fc40.aarch64/gtk/gtkmain.c:1270
#17 0x0000aaaaaaae78e8 [PAC] in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/pidgin-2.14.12-8.fc40.aarch64/pidgin/gtkmain.c:947
```
